### ISSUE TITLE
TypeError: jQuery(...).autocomplete is not a function

### ISSUE THREAD

**Issue by chandrumcd** [Strategery-Inc/Magento-InfiniteScroll#104]
I'm getting the error mentioned after installing the infinite scroll.

Please help me sort this out :(

Thanks in advance for your help!!!
![infinite scroll](https://cloud.githubusercontent.com/assets/10278284/8391323/caf0427c-1cdc-11e5-9520-6ab3269fd33b.PNG)

**Comment by janmyszkier** [comment]
@chandrumcd: infinite scroll doesn't use autocomplete so this is probably bad implementation of the other feature implemented - the one that makes use of autocomplete. possibly wrong usage of jquery inclusion or noconflict usage. 
Also make sure you give the url the problem exists on. We cannot understand the issue (not to mention analyze/debug) from a jpg file.

If you'd like to hire one of our developers for an hour or two in order to help you fix this issue please email us at: contact (at) strategery (dot) io
