### ISSUE TITLE
Not working in the layered navigation result page

### ISSUE THREAD

**Issue by chandrumcd** [Strategery-Inc/Magento-InfiniteScroll#107]
Hi,

I am using Layered Navigation(Filter) option from my custom theme. So the infinite scroll not working in the Layered navigation result page.

Please help me to add infinite scroll in my custom Layered Navigation ajax module.

Regards,
Chandra Sekar.M

**Comment by janmyszkier** [comment]
@chandrumcd : you didn't give us enough information to debug the issue, but if the layered navigation is not the one that magento comes with, I'm afraid we can't help you much because we don't have access to your extension / code / theme. You might want to ask the extension maker for the support as so far we confirmed our extension working on all default releases.

We can help you out with your issue if we have access to your code. If you'd like to hire one of our developers for an hour or two in order to help you fix this issue with your custom extension, please email us at: contact (at) strategery (dot) io

**Comment by chandrumcd** [comment]
Hi,

Thanks for your reply.

Please send the steps to add the infinite scroll to the custom category listing page.

Thanks and regards
Chandra Sekar

**Comment by janmyszkier** [comment]
@chandrumcd:
detailed description of how to do this is available at: https://github.com/Strategery-Inc/Magento-InfiniteScroll

Please not that point 2 of [Installation](https://github.com/Strategery-Inc/Magento-InfiniteScroll#installation) is explained in detail in [Configuration](https://github.com/Strategery-Inc/Magento-InfiniteScroll#configuration) and the "selectors" are the same as the css selectors, feel free to compare these with [demo store](https://github.com/Strategery-Inc/Magento-InfiniteScroll#demo)
