### ISSUE TITLE
Offset setting not working

### ISSUE THREAD

**Issue by rishiraj87** [Strategery-Inc/Magento-InfiniteScroll#124]
Hi,

I'm trying to enhance the user experience by loading contents of the next page well before the user has scrolled to the bottom of the page. I have changed the buffer setting from 150 px to 400 px all the way till 4000 px, but I see no change.

To validate this, I checked in Inspect element -> Network and observed when the contents of next page started loading. I found that whatever the value of offset setting, it had no effect on the time of loading.

Additional info : I have Lesti Full Page Cache installed and et_oxynic theme. Current offset value - 400

Website URL for testing -> www.rekinza.com/clothing

**Comment by rishiraj87** [comment]
Hi,

someone please help !

**Comment by gabrielsomoza** [comment]
Damian could you take a look to see if there's a bug in our extension? @rishiraj87 just so you know: we can only fix bugs in the extension itself. If you need dev support please contact us at contact (at) strategery (dot) io

**Comment by damian-pastorini** [comment]
Hi @rishiraj87 , for what I see in your page this is not an issue, the scroll started to load long before I hit the bottom of the page, but it took some time to load the next page that's why you still see the loading and the moment when the next set is rendered.
I would recommend you to improve your website response time and speed to avoid that.
Also you can make the page load less items, like 12 instead 24, because small sets of products will be loaded faster.
