### ISSUE TITLE
Not wokring on a Custom Theme.

### ISSUE THREAD

**Issue by prashanthpg** [Strategery-Inc/Magento-InfiniteScroll#126]
Hi,

"Loading the next set of posts..." does not go and products wont load.
http://www.pixelfly.in/qrocity/index.php/living/sofas/fabric-sofa.html

Magento Version: 1.9.2.2
Magento Theme: Custom
Strategery_InfiniteScroll2 Version: 3.2.1

and i have many other plugins installed. It works fine on a clean install.

Thanks,
Prashanth

**Comment by gabrielsomoza** [comment]
See if this article in the Wiki section helps: [Nothing Happens, Although the "Loading Next Page" Message is Visible](https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Nothing-Happens,-Although-the-%22Loading-Next-Page%22-Message-is-Visible).

Closing this ticket for now, but we can re-open later if necessary.

**Comment by prashanthpg** [comment]
Have managed to make it work. Works fine on a category page but not on vendors/brand page. Why is that?

http://www.pixelfly.in/gc/index.php/ves-brand/boca-do-lobo.html

**Comment by gabrielsomoza** [comment]
If the brand page is a CMS page (or anything else other than a category page) then it won't work by default. The reason is that CMS pages can take all kinds of contents within them, and sometimes its just static content, so there's no way for us to consistently provide infinite-scrolling on CMS pages.

If you're showing products on those brand pages I recommend you set them up as category pages with static CMS blocks. Then it should work. 

But if that's not possible / not practical and you can only set them up as CMS pages then I'm afraid you'll have to integrate InfiniteScroll into them manually. To do that you'll have to:
# Look at the scripts that we're injecting into Category pages and manually inject them into the CMS pages where you want the functionality.
# Look at the configuration script (that's also injected into Category pages) and do the same as above, but also changing the selectors accordingly to make sure they reflect the structure for the CMS page.
# Normally that would be all, but you may also have to hook into some of the events fired by the IAS library if you have to decorate them with behaviour.

Hope this helps!
