### ISSUE TITLE
Product data fetched, but not displaying

### ISSUE THREAD

**Issue by amitabhaghosh197** [Strategery-Inc/Magento-InfiniteScroll#127]
Hi, 
we are having an issue with the infinite scroll. On scroll, the ajax scroller is displayed. 
Yet the data is not displayed. 

On inspection using browser tools, it can be seen that the data is fetched in the json, however, the list of products are not displayed. 

Further, the url also shows ?p=2 indicating the next page. 
Please let us know a solution to this issue. 

Test Site: http://lab-3.sketchdemos.com/P-455-realestate-test/building-materials.html 

rgds

**Comment by atiteam** [comment]
Hi There, your test page loads the next page once you click the LOAD MORE PRODUCTS button.
I have a similar issue, firebug shows it fetches result but not injecting to the div and no other js error.
Any suggestion?

**Comment by gabrielsomoza** [comment]
@atiteam thanks for your comment. If the result is fetched but doesn't get injected then there could be two reasons:

1. Maybe the page loaded via AJAX doesn't have any products. Check that by opening the page's URL manually on a browser tab.
2. Otherwise, check that the selectors are configured properly in the extension's config area. We use them to identify which are the products and where to inject them.

Hope that helps. Setting status of the ticket to "closed" for now because both of these issues are configuration issues and not bugs in our extension. And we can still continue our conversation even while its closed. 

If we do find a bug we'll re-open the ticket of course.

**Comment by atiteam** [comment]
Hi There,

I think I just found new conflict with your extension. By the way great job.
This is the conflicting extension preventing to fetch new data to the canvas:
http://www.magentocommerce.com/magento-connect/magehouse-free-ajax-layered-navigation-toolbar-with-price-slider-2-2-0.html <http://www.magentocommerce.com/magento-connect/magehouse-free-ajax-layered-navigation-toolbar-with-price-slider-2-2-0.html>
If I figure out how I let you know.
Keep in touch,

Atiteam

**Comment by gabrielsomoza** [comment]
Thanks for the info. We started building a page where we'll list extensions that are known to cause problems, and potentially some solutions. If you find a way to fix this particular extension could you please let us know so others in the community can benefit from the fix?

**Comment by dev2jbsols** [comment]
Hello,

I am also facing same issue that Magehouse_Slider not compatible to infinte scroll extension. Have you found any solution of this? How To fix it? Please share here.

Thank You
