### ISSUE TITLE
Duplicate/Missing products

### ISSUE THREAD

**Issue by bouwkampioen** [Strategery-Inc/Magento-InfiniteScroll#128]
Upon scrolling down when selecting the "best match" ordering method, when scrolling down (thus loading next batch of produchts), it is loading some products twice, and some others are missing.

This does not happen when ordering on "price" level, but we don't want this..

Any idea what might be wrong?

**Comment by gabrielsomoza** [comment]
What happens if you manually (without scrolling down) visit the second, third (etc) pages: are those duplicate products present in those other pages?

To visit those other pages you may have to manually append ?p=2 (or similar) to the end of the URL

**Comment by bouwkampioen** [comment]
Hello,

 

We don’t work with pages, but if I do it manually it is still showing the same issue. Once scrolling down (and thus loading the next batch of products) some products are duplicate. Its as if it doesn’t take in account the previous set of loaded articles…

 

I see that there we don’t have the youngest version of the plugin installed, so maybe we should try this out first. 

But i wanted to mail you to see i fit was a common bug with a simple possible fix or not :p

 

Thanks for the fast response :)

 

 

Best regards – Meilleures Salutations – Vriendelijke groeten
 
Olivier Leus
 <mailto:info@bouwkampioen.be> info@bouwkampioen.be

+32 472 06 44 56


Pontstraat 54a
9090 Melle
Belgium
www.bouwkampioen.be

Disclaimer
This message and its attachments are sent in good faith and for information purposes only. They can not be considered as binding.

 

 

 

Van: Gabriel Somoza [mailto:notifications@github.com] 
Verzonden: dinsdag 1 december 2015 09:54
Aan: Strategery-Inc/Magento-InfiniteScroll <Magento-InfiniteScroll@noreply.github.com>
CC: bouwkampioen <olivier@bouwkampioen.be>
Onderwerp: Re: [Magento-InfiniteScroll] Duplicate/Missing products (#128)

 

What happens if you manually (without scrolling down) visit the second, third (etc) pages: are those duplicate products present in those other pages?

To visit those other pages you may have to manually append ?p=2 (or similar) to the end of the URL

**Comment by gabrielsomoza** [comment]
Ok, thanks. Let me know how it goes. Do make sure that you didn't disable pagination (pages) because our plugin requires that functionality to be intact in order to work properly: what our plugin does is to 1) hide the pagination controls from the user, 2) fetch the next page of products in the background, 3) inject the new products into the current page.

**Comment by gabrielsomoza** [comment]
Will close this ticket for now - we can re-open once you confirm if the newest version also has the issue - even with pagination enabled.

**Comment by bouwkampioen** [comment]
Hey,

 

We updated the plugin. However, it is still showing duplicate products and missing other products, when selecting the “best position” view option and scrolling down.. It does work when ordering on “price” attribute though… Any ideas? 

 

Van: Gabriel Somoza [mailto:notifications@github.com] 
Verzonden: dinsdag 1 december 2015 10:30
Aan: Strategery-Inc/Magento-InfiniteScroll <Magento-InfiniteScroll@noreply.github.com>
CC: bouwkampioen <olivier@bouwkampioen.be>
Onderwerp: Re: [Magento-InfiniteScroll] Duplicate/Missing products (#128)

 

Ok, thanks. Let me know how it goes. Do make sure that you didn't disable pagination (pages) because our plugin requires that functionality to be intact in order to work properly: what our plugin does is to 1) hide the pagination controls from the user, 2) fetch the next page of products in the background, 3) inject the new products into the current page.

**Comment by gabrielsomoza** [comment]
@bouwkampioen do you have a page I can visit where I could see the issue and check why its happening?

Also: is pagination enabled on that category?

**Comment by bouwkampioen** [comment]
Hello Gabriel,

 

http://www.bouwkampioen.be, just go to a subcategory, enable ordering “best match” “positiie” and scroll down. You’ll see certain products load again even when showing on first batch of loaded products.. and in the end some others are missing..

 

Coder claims pagination is on.

 

Van: Gabriel Somoza [mailto:notifications@github.com] 
Verzonden: dinsdag 8 december 2015 11:26
Aan: Strategery-Inc/Magento-InfiniteScroll <Magento-InfiniteScroll@noreply.github.com>
CC: bouwkampioen <olivier@bouwkampioen.be>
Onderwerp: Re: [Magento-InfiniteScroll] Duplicate/Missing products (#128)

 

@bouwkampioen <https://github.com/bouwkampioen>  do you have a page I can visit where I could see the issue and check why its happening?

Also: is pagination enabled on that category?

**Comment by gabrielsomoza** [comment]
Looks like you're using an AJAX-based layered navigation extension. That's probably what's causing issues with ours. See this page for a few more details: https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/3rd-party-Extension-Conflicts

What layered-navigation extension are you using? I'd like to add it to that page so that other people can be aware of this.

As you'll see in that page, the only way around it is to integrate both extensions with each other. That has to be done manually by a developer.

**Comment by bouwkampioen** [comment]
We are using AITOC Layered Navigation Pro.

Thanks for the clarification. As our coder couldn’t fix the issue himself, I believe the only solution will be to find a replacement fort he infinite scroll extension we are using from you guys :(

 

Thanks for support tho!

 

Cheers

 

Van: Gabriel Somoza [mailto:notifications@github.com] 
Verzonden: dinsdag 8 december 2015 12:14
Aan: Strategery-Inc/Magento-InfiniteScroll <Magento-InfiniteScroll@noreply.github.com>
CC: bouwkampioen <olivier@bouwkampioen.be>
Onderwerp: Re: [Magento-InfiniteScroll] Duplicate/Missing products (#128)

 

Looks like you're using an AJAX-based layered navigation extension. That's probably what's causing issues with ours. See this page for a few more details: https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/3rd-party-Extension-Conflicts

What layered-navigation extension are you using? I'd like to add it to that page so that other people can be aware of this.

As you'll see in that page, the only way around it is to integrate both extensions with each other. That has to be done manually by a developer.

**Comment by gabrielsomoza** [comment]
Sorry to hear that @bouwkampioen! If you find any extension that integrates nicely with AITOC Layered Navigation we'd really appreciate it if you could let us know (if not too much trouble) so we can see how they did it.

The reason I ask that is that I honestly can't imagine there will be any extension that can automatically integrate with other AJAX-based Layared Navigation extensions, simply because the mechanics of an AJAX-based navigation are bound to collide with those of an infinite-scroll extension. So unless AITOC themselves released an InfiniteScroll extension that's compatible with their own Layered Navigation tools, I don't think these two types of extensions can "understand" each other without manual intervention.

If at any point you feel like you'd like to integrate manually please feel free to contact us: we can provide a developer who can do it within a few hours at an accessible price.

**Comment by minindamiddle** [comment]
Hello Gabriel!

I have the same issue after last two updates(

**Comment by gsomoza** [comment]
@minindamiddle unfortunately we don't have a solution for this, see [my answer here](https://github.com/Strategery-Inc/Magento-InfiniteScroll/issues/128#issuecomment-163154237)

**Comment by gsomoza** [comment]
@minindamiddle keep in mind this ticket is for an issue with the AITOC Layered Navigation extension. If you're not using it then you might be experiencing a different issue.

**Comment by minindamiddle** [comment]
Thank you for reply. There is the only option to downgrade. What last version is stable for this issue?

**Comment by gsomoza** [comment]
If you don't use AITOC Layered Navigation then this issue might not apply to you. Do you use any kind of AJAX-based layered navigation?

**Comment by minindamiddle** [comment]
I found out that your extension is not relate to this issue. This bug is not in all categories, only in new. I fixed it by set manually item position in category (1,2,3,4... etc). But the reason of this issue is unknown. Manually visit pages is working fine. Other ordering methods (name, price) also are fine.

**Comment by gsomoza** [comment]
Glad you could fix it! If you think other people could have the same issue, would you consider contributing a few lines for how to solve it in our Wiki? This extension is open-source and free to use, so we rely on input from people like you to make it better for everyone.
