### ISSUE TITLE
Confliction with custom theme extensions(Layered navigation and lazy loading)

### ISSUE THREAD

**Issue by Manisha-opax** [Strategery-Inc/Magento-InfiniteScroll#136]
Hi,

I am using your extension on one of my dev site and its working as expected for normal category pages except that its not loading images which is the issue 1 and second is its not working with layered navigation.
So, two issues:
#issue1: not loading images
#issue2: not working with em themes layered navigation

Thanks,
Manisha Sharma

**Comment by gabrielsomoza** [comment]
Looks like your issues are related to these two articles in our wiki:
* https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Functionality-Issues-After-Loading-Next-Page
* https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/3rd-party-Extension-Conflicts

Hope that helps!

**Comment by Manisha-opax** [comment]
Hi Gabrielsomoza,

I have looked into the both links but it didn't helped me.
Please advise.

Thanks,
Manisha Sharma

**Comment by gabrielsomoza** [comment]
Hi Manisha, I recommend you consider hiring a PHP developer (maybe even a Magento developer) to help you with this. Since this is a free plugin I'm afraid we can't help with integration issues..

If you're interested in hiring one of our certified Magento developers please email us: contact (at) strategery (dot) io
