### ISSUE TITLE
Ultimo theme + infinite scroll [help]

### ISSUE THREAD

**Issue by davirs** [Strategery-Inc/Magento-InfiniteScroll#150]
Hi! I already read about [Functionality Issues After Loading Next Page](https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Functionality-Issues-After-Loading-Next-Page). And it´s exactly my problem. Some elements are missing while the first set of results does work.

this is a demo at grid page: http://ultimo.infortis-themes.com/demo/fifth/women.html

I need some help to put infinite scroll to works with ultimo theme.
How I need to call theme funcion and replace it at ias function:
```
ias.on('rendered', function(items) {
    var $items = $(items);

    $items.each(function() {
        $('.tooltip', this).tooltip();
    });
})
```

another thing, I need to do this configuration at init.phtml?

**Comment by gsomoza** [comment]
The demo doesn't seem to have InfiniteScroll enabled, could you check that?

Another thing: what function do you need to call on the new elements in order to decorate them?

**Comment by gsomoza** [comment]
Marking as ready-to-close because this isn't about a bug in our extension. Will wait for feedback from reporter before closing though.

**Comment by davirs** [comment]
Original Ultimo demo hasn't infinite scroll, but you can view hover functions.

Here is my demo with ultimo+infinite scroll http://goo.gl/QStT2Z

**Comment by damian-pastorini** [comment]
@davirs please check our last implementation and documentation about the infinitescroll events maybe that could help you to fix the issue with the custom theme.

**Comment by davirs** [comment]
I already read your documentation, if I had achieved I would not be asking for help... So I still need help to put this plugin to load hover elements.

Another thing, your demo not works.

![screenshot_22](https://cloud.githubusercontent.com/assets/4355062/14798823/d7478892-0b0f-11e6-9c8b-313b0adf822b.png)

**Comment by anurag2701** [comment]
Can you guys please help me to find the decoration script, so that we can fix the infinite scroll issue with it.

**Comment by damian-pastorini** [comment]
hi @davirs , @anurag2701 , 
In one of our last releases we included the following:
$(document).trigger( "infiniteScrollReady", [window.ias]);
If you listen the infiniteScrollReady you will be able to reach window.ias and from there include the JS code of your custom theme inside the on render event, like:

window.ias.on('rendered', function(items) {
    var $items = $(items);
    $items.each(function() {
        $('.tooltip', this).tooltip();
    });
})

Since this is not an issue in the extension itself we can't give you free support, if you like to hire some support hours you can email us: contact (at) strategery (dot) io

Thanks!

**Comment by danieledr** [comment]
Hi, @damian-pastorini ,
in my Ultimo theme if I would display **on hover** name and price of products, the infinite scroll don't work from second page, display only products image!
Please help me.
Regards

**Comment by damian-pastorini** [comment]
Hi @danieledr , you will probably need to apply some custom code to run the JavaScript from your theme after the InfniteScroll loaded the next products page.
To do that you can use an observer like the one I commented before:
```
window.ias.on('rendered', function(items) {
    // here your theme's custom code.
});
```
But as I commented before since this is not an issue in the extension itself we can't give you free support, if you like to hire some support hours you can email us: contact (at) strategery (dot) io

Thanks!
