### ISSUE TITLE
Tool bar viewing product number (1 to 9 of 31) not updating

### ISSUE THREAD

**Issue by domwhooley** [Strategery-Inc/Magento-InfiniteScroll#155]
I looked through all the open tickets and couldn't find this issue. As the title suggests, when loading the page 2 still displays first pages amount of products numbers. Any ideas how to fix other than hiding the tool bar? Magento EE 1.13.1.0, Stategy Infinite Scroll 2.3.0. 

Thanks,
D

**Comment by damian-pastorini** [comment]
Hi @domwhooley , we fixed a lot of issues over the new versions and mostly in the last one, please update InfiniteScroll and let us know if the issue continue.

**Comment by domwhooley** [comment]
Hi,

Thanks for replying. 

I have been working with the Ecommerce Team who have helped me iron out a few issues getting yours and theirs (SEO Nav) extensions to play nice. As part of that they advised me to update your plug which I did yesterday with the latest version I could find here https://github.com/Strategery-Inc/Magento-InfiniteScroll <https://github.com/Strategery-Inc/Magento-InfiniteScroll>. When I check the file creation date it says 9th May 2016, is that the latest version?

The site in question is my dev version http://dev.markuslupfer.com/women <http://dev.markuslupfer.com/women>. I assumed the issue might be with the scrolling plugin but if you get a chance maybe you can tell me if I should maybe go back to the ET guys, or maybe you can offer an idea as to a fix?

Thanks,
Dom 

  <http://domwhooley.com/>
Dom Whooley <mailto:dom@domwhooley.com>
+44 (0)7737 216 225 <tel:+44-7737-216-225>
domwhooley.com <http://domwhooley.com/>

**Comment by damian-pastorini** [comment]
Hi Dom,
 
Yes, the last version is the one in GitHub
<https://github.com/Strategery-Inc/Magento-InfiniteScroll>
https://github.com/Strategery-Inc/Magento-InfiniteScroll from 7 days ago.
 
In order to debug the issue you can:

*	

	Enable the extension debug mode and check if there are any errors in
the console.
*	

	Since you have a custom theme you need to make sure that all the
extension selectors are properly configured (System / Configuration /
InfiniteScroll / Selectors).

Unfortunatelly since that's not an issue in the extension itself we can't
give you free support, but if you like you can hire our development services
so we can assist you with the issue, just email us at
<mailto:contact@strategery.io> contact@strategery.io.
 
Best,
 

Regards,


  <http://usestrategery.com/strategery-icon.png> 

Damian A. Pastorini
Director of Operations
Strategery, Inc. 


(skype) damian.pastorini

(us) +1 888 575 7872 ext. 502

(be) +32 25 88 42 44 ext. 502


 

  _____
