### ISSUE TITLE
infinitescroll not working 

### ISSUE THREAD

**Issue by tapati** [Strategery-Inc/Magento-InfiniteScroll#157]
Hello,

I have successfully installed your plugin. I am using my own custom theme. So that i copied the "strategery"  folder into my theme template folder and also copied the strategery-infinitescroll.xml into my layout folder. And then clear cache. But still it is not coming in admin /System / Configuration / Catalog / Infinite Scroll.
       Can you please help me out ? My site URL is http://coralconcept.in/shoponline/clothing . I want to auto load page after 24 items showing so that i have set  system > Catalog>frontend   Products per Page on Grid Allowed Values 24,48,72 . 

Thanks
Tapati Paul

**Comment by damian-pastorini** [comment]
Hi @tapati , I just updated the README.md file, the correct path to the configuration is:
System / Configuration / Strategery / Infinite Scroll
If you get a 404 you will need to re-login in the admin.
In that section you will need to correct the selectors for your theme since I don't see any of the default ones.
Unfortunatelly since that's not an issue in the extension itself we can't
give you free support, but if you like you can hire our development services
so we can assist you with the issue, just email us at contact@strategery.io.

Best,
