### ISSUE TITLE
Infinite auto page loading not working 

### ISSUE THREAD

**Issue by tapati** [Strategery-Inc/Magento-InfiniteScroll#159]
Hello 
I have successfully installed this add on . But its not working with my custom theme. My site Url is http://coralconcept.in/shoponline/ . Please help me out ASAP.

Thanks 
Tapati Paul

**Comment by damian-pastorini** [comment]
Hi @tapati , in a quick look on your site you have several JS issues (I can see them just by opening my browser console), any of those issues could be preventing the InfiniteScroll to work properly.
Additionally your custom theme doesn't use any of the default Magento styles so you will need to modify the InfiniteScroll configuration with the proper selectors to detect items, containers, toolbar and pager links (you can check those in the System / Configuration / Strategery InfiniteScroll section).
Unfortunatelly since the issue is not in the extension itself we can't
give you free support, but if you like you can hire our development services
so we can assist you with the integration, just email us at contact@strategery.io.

**Comment by stefan68** [comment]
I think you can try this extension: http://bsscommerce.com/magento-infinite-scroll-for-magento-2.html
It works well as described

**Comment by gsomoza** [comment]
@stefan68 are you seriously recommending another extension (competition) on this extension's issue tracker? What's worse: the extension you mentioned is not free (like this one) and it will probably have the same issues anyway, so you're not really solving any issues.

Since I don't see much activity from you in Github, I'll have to assume that you're somehow affiliated to that extension and ban you for improper use of our issue tracking tool.
