### ISSUE TITLE
InfiniteScroll gets Slow after a couple hundred products

### ISSUE THREAD

**Issue by cojaco** [Strategery-Inc/Magento-InfiniteScroll#160]
Hello,

when I installed the new 3.5 version of infiniteScroll i realised that in very big productlist its getting slow and slower the mor products are alread loaded.

So e.g I have a list of 1200 Products, a page is 12Products big and the first ten times or so its very fast the the spinner occurs and new products are loaded.

But after this ten times it takes more and more time till the spinner appears.

which is a little confusing because a customer could think the end of the list is reached.

**Comment by gsomoza** [comment]
As far as I know there's nothing we can do about this. Just how slow it gets will depend on the device, but browsers do tend to slow down considerably whenever there are a lot of elements on the page.

I recommend fixing this on the front-end with custom code. Try hiding the elements that are not in the viewport so that the browser doesn't have to even consider rendering them. 

Not even sure if that will help much. But even if it does then that's not something that can be part of this plugin because the implementation will vary from shop to shop.

**Comment by gsomoza** [comment]
Well, there might be something we can do about when the spinner appears. @damian-pastorini can we make it appear early? E.g. right before the ajax request is sent?

**Comment by cojaco** [comment]
Hi gsmonza,

thank you for your answer. If the spinner could appear quicker, that would be very helpfull allready.

**Comment by damian-pastorini** [comment]
Hi @gsomoza , @cojaco , the spinner is already been displayed in the first ias event (next), which is triggered by the scroll event when the user reach the scroll buffer.
I don't think we can fix this if the browsers starts to delay the spinner display because an memory issue.

**Comment by gsomoza** [comment]
That's what I thought, its already being fired as early as possible but a slow browser would just take long to start rendering it. Let's keep this issue in mind to see if we can figure out any other solutions at some point in the future.

**Comment by cojaco** [comment]
thank you guys!

**Comment by gsomoza** [comment]
No problem, its a pity we couldn't find a solution for this!

**Comment by cojaco** [comment]
An idea, how about, every lets say ten pages, the previous content is unloaded from the dom,
then if you scroll up to that place or with an offset before, the previous pages are loaded again.

And after ten pages scrolling up, the last pages are deleted from the dom.

Does that make any sense?

**Comment by damian-pastorini** [comment]
Actually not a clue, never hear about that, the infinitescroll nevers unload content from the doom, could be a browser behavior? Did you tested it cross-browser?

**Comment by cojaco** [comment]
No, I meant, unloading or detach invisble products (products that are not in the viewport anymore) from the dom could be a solution for the slowing down problem.

In that way the browser hasn't to draw all theese hundreds of products.

The tricky part would just be to reattach the elements before they become visible in the viewport.

**Comment by gsomoza** [comment]
@cojaco I thought about doing that too, rendering will theoretically be faster. But we'd have to find answers to the following concerns:

1. Since we'd be making several calculations and then updating the DOM *as the user scrolls up/down*, the scrolling experience itself will probably remain quite poor - not only jumpy (due to the constant spatial changes to the DOM which will cause the scrollbar's range to change), but also probably still quite slow: although each frame will be rendered faster, the processing time between frames will increase considerably. The result will be a similarly bad experience - or more likely even worse.
2. The actual implementation of this behaviour in Magento is very coupled to the front-end. For example if we simply detach elements from the DOM, all JS decorating functionality around those elements will probably be lost unless its re-initialized. But that intialization is very vendor-specific. For example,  catalog color swatches provided by a 3rd-party plugin might require their own init calls after the element is re-inserted into the DOM. 

These are the biggest drawbacks in my opinion. If there are ways to work around them we should probably examine them in a PoC (e.g. JSFiddle or so). I find it personally hard to find a way to make this work such that it won't require developer integration on the end-user side, especially since each shop is so unique on its front-end.

**Comment by cojaco** [comment]
@gsomoza 

I was playing arround with it over the weekend, but I'm still struggeling to reatach detached elements.

Here is what I tried:
https://jsfiddle.net/pg083x17/4/
pretty messy

But the Idea is to:
wrap x elements
calculate the height of the wraps and set it inline css, to prevent jumping and to reduce elements. (its probably not so good for responsive / screen resize)

Than on scroll check which of the wraps are out of viewport (+ some offset)
store the content of this out of view wraps and detach this content.
check if "out of view" wrap comes into viewport again atach its content to this wrap and execute a callback on all visible wraps.

**Comment by gsomoza** [comment]
Wow: `Infinity` is amazing, works really fast! I think you should consider making that one work, if anything.

But yes, indeed: re-attaching elements will be difficult in Magento, even with something like Infinity. I can't think of a way to do it generically, so I don't think this feature could make it to the core of this extension (even though it would be awesome). However as a merchant or as a theme author, doing this is definitely worth considering.

What I'd suggest is the following:

1) Try to find a way to make Infinity work with IAS. You'll probably have to hook to the init script of IAS, or possibly even to JS event we trigger from our extension after initializing IAS. Another option, though a bit more radical, would be to actually ditch IAS in favour of using Infinity for everything (assuming Infinity has the ability to load the next page of products in a similar way that IAS does?).
2) Find a hook from Infinity where you can apply JS to an element (aka "decorate it") after it has been attached. Hook to that with a custom listener.
3) Find the decoration logic that needs to be applied by Magento and any other 3rd party plugins that may modify the behaviour of catalog items (e.g. js related to color swatches or "quick view" popups, etc). Attach that logic to the custom listener.

**Comment by damian-pastorini** [comment]
Hi guys, I would like to suggest to research about memory leaks and how to test or fix them, like:
- http://stackoverflow.com/questions/19621074/finding-javascript-memory-leaks-with-chrome
- https://auth0.com/blog/2016/01/26/four-types-of-leaks-in-your-javascript-code-and-how-to-get-rid-of-them/
Maybe there's a way to fix this by detecting where the memory is been consumed and rewriting that pice of code (not easy but possible).
Best,
