### ISSUE TITLE
Infinite scroll not working in magento 1.9.1

### ISSUE THREAD

**Issue by PawanKumarN** [Strategery-Inc/Magento-InfiniteScroll#183]
Hi,
I'm facing issues with infinite scrolling.
My Magento version is 1.9.1.0 and have  rwd theme customized
I have installed the extension using 
https://marketplace.magento.com/strategery-strategery-infinitescroll2.html
i saw demo 
http://demo.usestrategery.com/infinite-scroll/infinitescroll.html?p=8
in demo working fine in my magneto it is not working 
checked some links i found one link
https://stackoverflow.com/questions/30455267/strategery-infinitescroll-not-working
in the above link i fallowed 2 answer but no luck
please guide me

**Comment by gsomoza** [comment]
Have you been able to go through the [Wiki](https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki) for configuration instructions and fixes for common integration issues?

**Comment by damian-pastorini** [comment]
Hi @PawanKumarN , do you still have the issue?
I'm pretty sure some of the customizations could be generating the issues with the extension.
I also wanted to take the opportunity to just mention that we only offer support for bug fixes on our extension. If you're having integration issues (e.g. related to the custom theme) then we won't be able to help much because this is a free extension. If you want commercial support you can email us at contact (at) strategery (dot) io
Best,
