### ISSUE TITLE
Errors with cache when update catalog template File

### ISSUE THREAD

**Issue by MAk-Antonio** [Strategery-Inc/Magento-InfiniteScroll#199]
Hello,
I  installed the module,
and work perfectly, except for problems when update template files ajax call return a old view of template,
and don't appear alterations in template file.
How could i Fix it?

**Comment by gsomoza** [comment]
Looks like you might have run into [this gotcha](https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Functionality-Issues-After-Loading-Next-Page). The documentation there gives a general idea of how to approach the issue.

Another possibility, if this is really only a cache issue, is that the cache is not really varying based on the "p" request parameter. In that case you're going to have to fix the cache so that it adds most request parameters to the cache hash.

I hope this helps. In either case this isn't really a bug on this plugin so I'll close the ticket, but feel free to follow-up with questions and I'll answer them if I have time.

**Comment by MAk-Antonio** [comment]
Sorry, but i can't see how i can fix it and how the IAS events can help me with this, still have the problem and the normal paginaton work perfectly. Have a Event, a exactly method to fix it?

**Comment by gsomoza** [comment]
I'm afraid I can't offer you an "exact" solution for this. If you're not an experienced Magento developer then I recommend hiring one at least so he/she can look into this particular issue and fix it. Unfortunately that's not something we can do for free..
