### ISSUE TITLE
Cannot scroll up when History is enabled

### ISSUE THREAD

**Issue by rsnare** [Strategery-Inc/Magento-InfiniteScroll#93]
The Enable History feature attaches a page number to the end of the URL as the user scrolls down the product list. This makes it so that, when the user clicks to view a product and then hit their back button, they are returned to the same page of the product list. However, the problem is that they are then not able to view any of the pages that come before that page. For example, if they click on a product on page 7 and then are returned to page 7, they cannot scroll up to view any of the products on page 1-6. I am not sure if this is a bug or expected behavior, because the same behavior is shown in the InfiniteScroll demo store. However, this seems like a poor user experience. Is there a way to enable History without preventing users from viewing the previous pages?

**Comment by gabrielsomoza** [comment]
This is more of an architectural issue, to address it we'd have to change a lot of things in Magento and in our extension. 

Automatically scrolling "up" is also not a real possibility because browser windows most times appear at the top - it would just trigger and make a mess of the user experience.

**Comment by gabrielsomoza** [comment]
Also, even that suggestion would get very complicated, very quickly, if you have a proxy-cache (e.g. Varnish) or if you're doing FPC with EE. In other words there are so many ramifications to doing something like this that it officially escapes the purposes of this simple extension.

**Comment by gabrielsomoza** [comment]
Having said that: if you're willing to contribute a PR that solves this problem elegantly you're more than welcome! It would be very interesting if we could find a simple solution to this problem.

**Comment by rsnare** [comment]
Thanks for the quick response, Gabriel. Making any modifications to the code is beyond my technical knowledge, so I will just disable the history and use the extension without the page numbers. That seems to be the best available option for my store and my customers. Thanks again!

**Comment by djfordz** [comment]
I need to resolve this issue for one of our clients, so I am going to attempt to tackle it and submit a PR here shortly.

**Comment by gabrielsomoza** [comment]
Great @djfordz! we're curious to see how you'll tackle it. I'm sure you already did it, but just in case: make sure you read the second comment above for some info on why I think its a complicated issue. 

Having said that: we look forward to your contribution!

**Comment by djfordz** [comment]
It is def a complicated issue, and will prob take me a few days...I am a Junior Magento Dev and am anxious to tackles something like this.

**Comment by gabrielsomoza** [comment]
If you're junior dev then I'd recommend you start with some other low-hanging fruit rather than tackle something like this: my opinion is that its just not a feasible feature. And I've never seen it implemented anywhere else on the Internet. There's probably  no good way of building it without compromising severely on other aspects such as UX or possibly even worse: the ability for this plugin to remain "generic" / theme-agnostic.

So that's my advice as a senior dev: this is an extremely tricky one and its better to start with easier issues. For example we could use some code or documentation to integrate with some of the layered-navigation extensions that are known to have conflicts [in this page](https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/3rd-party-Extension-Conflicts).

Having said that, and like I said before: if you're committed to doing it then I'd be interested in seeing a fresh approach to this old riddle :P
