### ISSUE TITLE
Second page deleting hash

### ISSUE THREAD

**Issue by Sebazz** [Strategery-Inc/Magento-InfiniteScroll#98]
Hello, i have some problems with yours plugin it works fine but one thing is going wrong. Look at this site: https://antidotestreet.com/picknmix.html

While i scroll down, script will lodaded page 2 (https://antidotestreet.com/picknmix.html#/page/2), now if i click on product, and come back <-, i got 404 error :( becaouse from url was deleted hash(#, https://antidotestreet.com/picknmix.html/page/2). Why? I have bad configuration? I found similar issue at ur repository but author solved problem by mail, no public :(

Can you give me fast reply? I will be pleased! Thanks a lot

**Comment by gabrielsomoza** [comment]
Looks like you have some plugin that removes the hashtag part of the URL in order to request it to the server. That seems to be causing this issue. For example if you manually go to https://antidotestreet.com/picknmix.html#/page/2 it will convert it to https://antidotestreet.com/picknmix.html/page/2

A possible workaround would be to limit that plugin's functionality by parsing the hashtag and converting everything else other than the "page/X" part into the main URL, and leaving that bit as a hashtag. 

Since this is not an issue caused by our plugin, specific details on how to fix that are beyond the scope of what we can offer as free support. Let me know if you're interested in hiring one of our developers to fix this for you.

**Comment by Sebazz** [comment]
Okay i found script jquery.ba-hashchange.min.js i deleted it, now hash didn't deleted but inifinity scrolling doesn't wok :(

**Comment by gabrielsomoza** [comment]
Is that change already here https://antidotestreet.com/picknmix.html#/page/2 ? cause I'm still getting the hash change thing.

**Comment by Sebazz** [comment]
Look now, i try to change some lines in script, w/o any effects..

**Comment by Sebazz** [comment]
I don't know what the hell is going on, now hash is still deleting, infinity scroll didn't wok ..

**Comment by gabrielsomoza** [comment]
Then the hash is either being deleted by some other script, or the script you wanted to remove wasn't really removed yet (most probable). I actually do see jquery.ba-hashchange.min.js still showing up in the page's source code.
