### ISSUE TITLE
conflict with search autocomplete

### ISSUE THREAD

**Issue by BadBuLLL** [Strategery-Inc/Magento-InfiniteScroll#99]

**Comment by gabrielsomoza** [comment]
Were you able to find what the problem was? If so we would appreciate it if
you could share the solution!

**Comment by BadBuLLL** [comment]
All I had to do is turn off jquery and it worked. Search autocomplete is now working 100%.
There is one strange thing though: if I turn on history and I click item on i.e. page 6, then click Back, it will now only show items from page 6, not item from page 1-6 as it was before I clicked back. Since Infinity scroll removed page numbers, customer can only go to page 7, 8,... but not on page 5,4,...?
BR
Samo

**Comment by gabrielsomoza** [comment]
That's a limitation of infinite scrolling in general: it wouldn't be practical to load all pages from 1 to X because it would consume tons of resources (e.g. imagine 100 pages at once) and would make this plugin more complicated by several orders of magnitude. 

There was another issue (closed) where we discussed this in more detail, including the idea of loading previous pages by scrolling "upwards" (which was also discarded).

**Comment by BadBuLLL** [comment]
Thank you for explanation, things are more clear now. I do miss back to top option at the end of catalog. Other than that, extension is working very good!
BR
Samo
